### ISSUE TITLE
[Toggle Model] Rename current Segment to something as ExactMatchingSegment 

### ISSUE THREAD

**Issue by kpicaza** [pheature-flags/pheature-flags#117]
**Epic:** https://github.com/pheature-flags/pheature-flags/issues/2 Toggle Model
**Package:** https://github.com/pheature-flags/toggle-model 

**Description:**

We want to create different types of segments, in the current implementation, we already got one type, Segment. We want to rename it something more explicit like ExactMatchingSegment. This way we will have the ability to create different Segment types maintaining the same naming convention, for example, InCollectionMatchingSegment.

\* *the naming convention is not already defined, we are open for suggestions;-D*

**Comment by xserrat** [comment]
Hi @kpicaza !

I found another adjective that may fits our case: `StrictSegment` or `StrictMatchingSegment`. What do you think? 

Anyway, the one you purpose is also understandable for me 🚀

**Comment by kpicaza** [comment]
Love that: `StrictMatchingSegment`. Is much more explicit :rocket:
