### ISSUE TITLE
[Toggle Model] Create a Segment type that finds a match in a collection of values

### ISSUE THREAD

**Issue by kpicaza** [pheature-flags/pheature-flags#118]
**Epic:** https://github.com/pheature-flags/pheature-flags/issues/2 Toggle Model
**Package:** https://github.com/pheature-flags/toggle-model 

**Description:**

Create a new segment type implementing the Segment interface. It should match when the given value is present in a segment's collection of values.

**Comment by xserrat** [comment]
Hi @kpicaza , I was checking this issue and the idea is to create a `Segment` that contains multiple segments so the match should be when the first segment matches or all segments must match?

This is the first approach I was thinking about:

```php
public function match(array $payload): bool
{
      foreach ($this->segments->all() as $segment) {
          if ($segment->match($payload)) {
              return true;
          }
      }
  
      return false;
}
```

So in this case, when the fist segment matches, it'll return `true`. Then, the `criteria` should be a merge of all segments' criteria.

What do you think?

**Comment by kpicaza** [comment]
Hi @xserrat :wave:, nice;-D,  this exactly the behavior of the EnableByMatchingSegment strategy type. 

![image](https://user-images.githubusercontent.com/1093654/115992512-64ec8400-a5ce-11eb-8abb-9d05f3bb3c9d.png), 

I was thinking of something like IdentitySegment, but with dynamic keys 

![image](https://user-images.githubusercontent.com/1093654/115992547-877e9d00-a5ce-11eb-849e-1a9048769325.png)
