### ISSUE TITLE
[Symfony-toggle] Allow multiple driver implementations

### ISSUE THREAD

**Issue by xserrat** [pheature-flags/pheature-flags#179]
**Epic:** https://github.com/pheature-flags/pheature-flags/issues/97 Symfony Toggle
**Package:** https://github.com/pheature-flags/symfony-toggle 

**Description:**

Allow running multiple driver implementations at the same time, in order to define different feature flags depending on the driver (`in memory` and `dbal` right now).

**Comment by kpicaza** [comment]
Thanks;-D. I think that we can do this as a core feature, applying chain decorators(like with Strategies and Segments). For example, we can imagine a ChainFeatureFinder that gets available toggles both from the in-memory finder and the Dbal finder as well.
