### ISSUE TITLE
Run GrumPHP used in the pre-commit hook in a Docker container

### ISSUE THREAD

**Issue by xserrat** [pheature-flags/pheature-flags#211]
In order to prevent installing PHP and XDebug in our host machine to run the pre-commit hook powered by GrumPHP, it could be a good solution running it in a Docker container.

**Comment by kpicaza** [comment]
Looks like a great idea, I suggest doing it as follows:

* Create docker image in DockerHub as `pheature-dev-php`
* then execute this image in the monorepo package
* also update the Grumphp config on each package

:rocket::rocket::rocket:
