### ISSUE TITLE
[laravel-toggle] Update Laravel package documentation 

### ISSUE THREAD

**Issue by xserrat** [pheature-flags/pheature-flags#223]
Epic: #221 Laravel Toggle
Package: https://github.com/pheature-flags/laravel-toggle
Docs: hhttps://pheatureflags.io/#/getting-started/laravel-package

## Description:

Update the documentation regarding the Laravel Toggle package with the following updates:
### Installation guide: 
* Explain how to install the package
* Explain the available drivers (inmemory, dbal)

### InMemory driver
* Explain what is and how to install
* Configuration
* Usage / Example

### Dbal driver
* Explain what is and how to install
* Configuration
* Usage / Example

### Rest API
* Explain what is and how to install
* Configuration
* Usage / Example

### Configuration section
* Display the full configuration reference and explain each property

Also, add minimal installation steps in the README package and add a link to the docs.

**Comment by kpicaza** [comment]
- [ ] Add same options as Symfony and Mezzio packages :rocket::rocket:
