### ISSUE TITLE
API Docs Malformed Code Examples

### ISSUE THREAD

**Issue by pcs289** [pheature-flags/pheature-flags#263]
There are malformed code examples on the API Documentation site in the following languages:
- HTTP
- PHP
- Go
- cURL

Instead of `[object Object]` it should include the object itself

**Comment by xserrat** [comment]
The places where the code examples are malformed are:
- [HTTP](https://api.pheatureflags.io/?http#pheature-flags-api):
![image](https://user-images.githubusercontent.com/5933658/193424888-68d59e99-61a6-4339-88aa-7c66c33147de.png)
- [PHP](https://api.pheatureflags.io/?php#pheature-flags-api):
![image](https://user-images.githubusercontent.com/5933658/193424899-781023b4-cc13-4dce-ac63-19dedfa4dea7.png)
- [Go](https://api.pheatureflags.io/?go#pheature-flags-api):
![image](https://user-images.githubusercontent.com/5933658/193424941-a0fca49a-af74-4945-8e5b-7676bba477fb.png)
- [cURL](https://api.pheatureflags.io/?shell#pheature-flags-api):
![image](https://user-images.githubusercontent.com/5933658/193424949-81640091-cf7b-41e9-995e-880e14387619.png)

Same issue occurred for these sections and only for the languages commented by @pcs289 :
- https://api.pheatureflags.io/?go#retrieves-the-list-of-features-for-the-given-identity
- https://api.pheatureflags.io/?go#retrieves-a-feature-for-the-given-feture-id-and-identity

The expected object definition is:
```json
"identity":{
  "identity_id": "string",
  "payload": {}
}
```

Repo to contribute: https://github.com/pheature-flags/api-docs

**Comment by pcs289** [comment]
This issue has been solved at https://github.com/pheature-flags/api-docs/pull/41
