### ISSUE TITLE
[pheature-flags] Add fabpot security checker action

### ISSUE THREAD

**Issue by kpicaza** [pheature-flags/pheature-flags#267]
**Is your feature request related to a problem? Please describe.**
We can add a Github action to check our package dependencies for security vulnerabilities.

https://github.com/marketplace/actions/the-php-security-checker

**Describe the solution you'd like**
I would like to get an automated report of any vulnerability in our dependencies

**Comment by pcs289** [comment]
An awesome approach to DevSecOps!
