### ISSUE TITLE
[toggle-core] Update issue template for bugs using new issue form in a YAML file

### ISSUE THREAD

**Issue by xserrat** [pheature-flags/pheature-flags#299]
In order to make easier the creation of bugs following a specific format, we should update the [markdown file](https://github.com/pheature-flags/pheature-flags/blob/1.0.x/.github/ISSUE_TEMPLATE/bug_report.md) into a YAML file.

See [Github Docs](https://docs.github.com/es/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms).

This epic contains:
* https://github.com/pheature-flags/pheature-flags/issues/300
* https://github.com/pheature-flags/toggle-core/issues/23
* https://github.com/pheature-flags/api-docs/issues/8
* https://github.com/pheature-flags/mezzio-toggle/issues/3
* https://github.com/pheature-flags/laravel-toggle/issues/3
* https://github.com/pheature-flags/php-sdk/issues/4
* https://github.com/pheature-flags/symfony-toggle/issues/3
* https://github.com/pheature-flags/toggle-crud-psr11-factories/issues/5
* https://github.com/pheature-flags/toggle-crud-psr7-api/issues/5
* https://github.com/pheature-flags/toggle-crud/issues/10
* https://github.com/pheature-flags/inmemory-toggle/issues/3
* https://github.com/pheature-flags/toggle-model/issues/8
* https://github.com/pheature-flags/dbal-toggle/issues/3
* https://github.com/pheature-flags/monorepo-changelog-filter/issues/3
* https://github.com/pheature-flags/toggle-ui/issues/2

**Comment by pcs289** [comment]
How about using this `bug_report` YAML file found at [toggle-ui PR#3](https://github.com/pheature-flags/toggle-ui/pull/3) to have all ISSUE_TEMPLATES standardized? Otherwise, do you think we should customize `bug_report` templates on a per-repo basis?

**Comment by xserrat** [comment]
Ouch! I didn't see your comment. I've just merged the first issue regarding this epic and I named the file as `bug.yml` directly. What do you think? See https://github.com/pheature-flags/pheature-flags/blob/1.0.x/.github/ISSUE_TEMPLATE/bug.yml . We could use a similar structure.

Regarding the customisation, I agree with you that we could customise them. For the issue #300 that it was a bug report for the `pheature-flags` repo, I've added a section called `Integration` with a dropdown of the three possible integrations: Standalone, Symfony, Mezzio and Laravel. I think that for Toggle UI we could set a dropdown for each component maybe... @kpicaza what do you think about that?

**Comment by xserrat** [comment]
@pcs289 , check also the https://github.com/pheature-flags/pheature-flags/blob/1.0.x/.github/ISSUE_TEMPLATE/bug.yml. I've set the two suggested labels `bug` and `triage`. The `triage` is added in order to help maintainers to filter by those issues pending to check by maintainers. I think that it's a good way to keep control about incoming bugs. After checking the bug and ensure that it's a real bug, we can remove the `triage` label to mark as "real bug". What do you think?

**Comment by pcs289** [comment]
@xserrat I am using the template at [PR#3](https://github.com/pheature-flags/toggle-ui/pull/3) for `toggle-ui` as the Integration dropdown is not needed.

**Comment by pcs289** [comment]
🚀
