### ISSUE TITLE
Create DockerHub Organization Account

### ISSUE THREAD

**Issue by pcs289** [pheature-flags/pheature-flags#46]
A DockerHub organization account should be created to host the prebuilt Pheature Flags Docker images

**Comment by luismartinmartinez** [comment]
Pau, yo necesito usar dockerhub? Me suena técnico-mandarín :)

**Comment by pcs289** [comment]
@luismartinmartinez suena y efectivamente es técnico-mandarín ahahaha si te interesa adelante pero si que es verdad que no lo necesitarás mucho. Creo que por eso cerré el issue.
